'use client'
import { useState } from 'react'
import Link from 'next/link'

import { BrandMark } from '@/components/brand'
const looks=[
 {name:'Um dia leve.',mood:'Casual',color:'#e7d9b6',bottom:'#82917a',items:['Camisa de algodão','Calça verde-sálvia','Tênis de lona'],note:'Tons naturais e tecidos leves. Uma composição confortável para acompanhar o cotidiano.'},
 {name:'Presença sutil.',mood:'Trabalho',color:'#b5c7d2',bottom:'#4c5661',items:['Camisa azul','Calça de alfaiataria','Sapato marrom'],note:'A camisa clara equilibra a alfaiataria escura. Linhas simples para novos encontros.'},
 {name:'Depois das seis.',mood:'Jantar',color:'#c98166',bottom:'#39423e',items:['Camisa terracota','Calça preta','Sapato marrom'],note:'Uma cor quente sobre uma base escura. Poucos elementos para mudar a energia do look.'}
]
function Piece({type='shirt',color}){
 return <svg viewBox="0 0 220 240" fill="none" aria-hidden="true">{type==='shirt'?<><path d="M72 30 94 19h32l22 11 51 41-27 42-23-16 7 119H64L71 97l-23 16-27-42z" fill={color} stroke="#373e3825" strokeWidth="2"/><path d="m94 19 16 24 16-24 12 15-17 25-11-16-11 16-17-25z" fill="#ffffff55" stroke="#373e3825"/><path d="M110 45v165M71 97l5-41M149 97l-5-41M72 201h75" stroke="#373e3830" strokeWidth="2"/>{[76,101,126,151,176].map(y=><circle key={y} cx="114" cy={y} r="2" fill="#555a4c80"/>)}<path d="M128 71h17v23h-17z" stroke="#373e3830"/></>:type==='pants'?<><path d="M65 20h90l12 198h-46l-12-126-10 126H52z" fill={color} stroke="#20272235" strokeWidth="2"/><path d="M65 36h90M109 36v56M72 39l-7 30M149 39l7 30M75 82l-8 123M142 82l10 123" stroke="#ffffff40" strokeWidth="2"/></>:<><path d="M39 104c9-4 27 18 44 19l28-29 28 9 12 35 40 19c13 7 17 24 3 31H35c-15-6-12-19-5-29z" fill={color} stroke="#33333330" strokeWidth="2"/><path d="M28 178h170M92 127l34 7m-25-18 30 8m-22-18 26 9" stroke="#fffaf0" strokeWidth="7"/></>}</svg>
}
export function Atelier(){
 const [selected,setSelected]=useState(0),[saved,setSaved]=useState([]),[view,setView]=useState('explore')
 const look=looks[selected],isSaved=saved.includes(selected)
 const toggleSave=()=>setSaved(current=>current.includes(selected)?current.filter(i=>i!==selected):[...current,selected])
 return <div className="atelier"><aside className="at-sidebar"><Link href="/" className="at-logo"><span><BrandMark className="brand-mark" size={30} /></span> Roupzy</Link><p className="at-side-caption">UM NOVO OLHAR<br/>{' '}PARA O SEU ARMÁRIO.</p><nav aria-label="Explorar demonstração"><button className={view==='explore'?'active':''} onClick={()=>setView('explore')}>▦ <span>Explorar</span> ↗</button><button className={view==='saved'?'active':''} onClick={()=>setView('saved')}>♡ <span>Meus favoritos</span> {saved.length}</button><a href="#como">◷ <span>Como funciona</span></a><Link href="/sobre">◎ <span>Sobre a Roupzy</span></Link></nav><div className="at-side-bottom"><span>↳</span><p>Você já tem<br/>{' '}um bom começo.</p><Link href="/cadastro">Conhecer o cadastro ↗</Link></div><Link className="at-help" href="/faq">Precisa de ajuda? ↗</Link></aside>
 <div className="at-main"><header className="at-top"><span>Seu estilo. Novas possibilidades.</span><div><span className="at-preview">Demonstração interativa</span><Link href="/login">Entrar ↗</Link></div></header><main><section className="at-intro"><div><span className="at-eyebrow">MENOS “O QUE VESTIR?”. MAIS VOCÊ.</span><h1>Abra espaço para<br/>{' '}<em>novas combinações.</em></h1></div><p>Redescubra suas roupas.<br/>{' '}Experimente ideias.<br/>{' '}Encontre o seu jeito.</p></section><div className="at-toolbar"><div><button className={view==='explore'?'selected':''} onClick={()=>setView('explore')}>O ateliê</button><button className={view==='saved'?'selected':''} onClick={()=>setView('saved')}>Salvos nesta visita ({saved.length})</button></div><span>Peças ilustrativas · explore à vontade</span></div>
 {view==='saved'?<section className="at-saved"><span className="at-eyebrow">SUA SELEÇÃO</span><h2>Ideias para guardar.</h2>{saved.length?<div className="at-saved-grid">{saved.map(i=><button key={i} onClick={()=>{setSelected(i);setView('explore')}}><Piece color={looks[i].color}/><strong>{looks[i].name}</strong><span>Abrir combinação ↗</span></button>)}</div>:<div className="at-empty"><span>♡</span><p>Seu primeiro favorito começa no ateliê.</p><button onClick={()=>setView('explore')}>Explorar combinações ↗</button></div>}</section>:<section className="at-workbench" aria-label="Ateliê de combinações"><div className="at-canvas"><div className="at-canvas-top"><span>ESTUDO DE ESTILO / 0{selected+1}</span><button onClick={toggleSave} aria-pressed={isSaved} aria-label={isSaved?'Remover dos favoritos':'Salvar combinação'}>{isSaved?'♥':'♡'}</button></div><div className="at-art"><div className="at-orbit"/><div className="at-shirt"><Piece color={look.color}/></div><div className="at-pants"><Piece type="pants" color={look.bottom}/></div><div className="at-shoe"><Piece type="shoe" color={selected===0?'#d7ccae':'#9d6d50'}/></div><span className="at-tag at-tag-one">01 / A base</span><span className="at-tag at-tag-two">02 / O equilíbrio</span><span className="at-handwriting">tudo começa<br/>{' '}com o que é seu ↗</span></div><div className="at-canvas-bottom"><span>Uma composição, outras possibilidades.</span><span>Experimente ao lado ↗</span></div></div><div className="at-compose"><span className="at-eyebrow">VAMOS EXPERIMENTAR?</span><h2>{look.name}</h2><p>Escolha um momento e veja a combinação se transformar.</p><div className="at-occasions" aria-label="Ocasião">{looks.map((item,i)=><button key={item.mood} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{item.mood}</button>)}</div><div className="at-look-details" aria-live="polite"><p>{look.note}</p><ul>{look.items.map((item,i)=><li key={item}><span>0{i+1}</span>{item}<span>↗</span></li>)}</ul></div><button className="at-primary" onClick={()=>setSelected((selected+1)%looks.length)}>Experimentar outra combinação <span>↻</span></button><span className="at-disclosure">Exemplos de estilo, sem análise de IA nesta demonstração.</span></div></section>}
 <section className="at-discover" id="como"><div className="at-section-heading"><h2>Um armário.<br/>{' '}<em>Muitos caminhos.</em></h2><Link href="/como-funciona">Conheça a proposta ↗</Link></div><div className="at-paths">{[['01','Comece por uma peça.','Uma foto dá início à organização do seu guarda-roupa.','+'],['02','Dê o seu toque.','Revise os detalhes e conte o que combina com você.','↔'],['03','Vista uma nova ideia.','Descubra possibilidades a partir das suas próprias roupas.','↗']].map(([n,title,copy,icon])=><article key={n}><div><span>{n}</span><b>{icon}</b></div><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="at-manifesto"><span>O MELHOR PONTO DE PARTIDA</span><h2>Já está no<br/>{' '}<em>seu armário.</em></h2><Link href="/recursos">Descubra a Roupzy ↗</Link><div aria-hidden="true"><BrandMark className="brand-mark" size={72} /></div></section></main><footer className="at-footer"><strong>Roupzy</strong><nav aria-label="Institucional">{[['sobre','Sobre'],['planos','Planos'],['contato','Contato'],['faq','Ajuda'],['privacidade','Privacidade'],['termos','Termos'],['cookies','Cookies']].map(([url,label])=><Link key={url} href={'/'+url}>{label}</Link>)}</nav><span>© 2026 Roupzy</span></footer></div></div>
}
